const express = require('express');
const router = express.Router();
const Joi = require('joi');
const journalController = require('../controllers/journalController');
const { protect } = require('../middleware/auth'); 
const licenseShield = require('../middleware/licenseShield'); 
const { validateBody } = require('../middleware/validate');

// 🛡️ Strict Schema for Mathematical Precision & Data Integrity
const journalEntrySchema = Joi.object({
    entryNumber: Joi.string().optional(), // Usually generated by backend
    period: Joi.string().pattern(/^\d{4}-\d{2}$/).optional(),
    documentDate: Joi.date().iso().required(),
    postingDate: Joi.date().iso().optional(),
    description: Joi.string().max(500).required(),
    sourceDocument: Joi.string().allow('', null).optional(),
    lines: Joi.array().items(
        Joi.object({
            account: Joi.string().hex().length(24).required(), // MongoDB ObjectId validation
            debit: Joi.number().min(0).default(0),
            credit: Joi.number().min(0).default(0),
            memo: Joi.string().allow('', null).optional()
        }).custom((obj, helpers) => {
            // Mutual Exclusivity: Cannot have both Debit and Credit
            if (obj.debit > 0 && obj.credit > 0) {
                return helpers.message('A single ledger line cannot contain both a debit and a credit amount.');
            }
            // Cannot have empty lines
            if (obj.debit === 0 && obj.credit === 0) {
                return helpers.message('A ledger line must have either a debit or a credit amount greater than zero.');
            }
            return obj;
        })
    ).min(2).required() // Strict Double-Entry minimum (must have at least 2 lines)
});

// 🛡️ Strict Voiding Schema
const voidSchema = Joi.object({
    voidReason: Joi.string().min(5).max(200).required() // Force them to type a real reason
});

// Secure all accounting routes behind your auth and license guard
router.use(protect);

// If you are actively using the licenseShield, uncomment the line below:
// router.use(licenseShield);

// 🟢 Standard Journal Entries (Now Armor-Plated)
router.route('/')
    .post(validateBody(journalEntrySchema), journalController.createJournalEntry)
    .get(journalController.getJournalEntries);

// 🟢 The Accrual Engine Endpoint
if (journalController.createAccrual) {
    router.post('/accrual', validateBody(journalEntrySchema), journalController.createAccrual);
}

// 🟢 Voiding Entries (Now protected by the voidSchema)
router.route('/:id/void')
    .post(validateBody(voidSchema), journalController.voidJournalEntry);
    
module.exports = router;